# Generated by Django 6.1 on 2026-09-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(default='1.0.0', max_length=50)),
                ('input_text', models.TextField()),
                ('predicted_category', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('prediction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_logs', to='grievances.grievance')),
            ],
        ),
    ]
