# Generated by Django 6.1 on 2026-09-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('POTENTIAL_INCIDENT', 'Potential Area Outage Cluster'), ('CONFIRMED_OUTAGE', 'Confirmed Feeder/Area Outage'), ('RESTORATION_IN_PROGRESS', 'Line Restoration Crew Active'), ('RESOLVED', 'Outage Cleared')], default='POTENTIAL_INCIDENT', max_length=30)),
                ('affected_substation', models.CharField(blank=True, max_length=150, null=True)),
                ('linked_complaints_count', models.IntegerField(default=1)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='departments.servicearea')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentGrievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_links', to='grievances.grievance')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_grievances', to='incidents.incident')),
            ],
            options={
                'unique_together': {('incident', 'grievance')},
            },
        ),
    ]
