# Generated by Django 6.1 on 2026-09-09 14:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('provided_category', models.CharField(blank=True, help_text='Category selected by consumer (optional)', max_length=100, null=True)),
                ('predicted_category', models.CharField(blank=True, choices=[('Power Outage / No Supply', 'Power Outage / No Supply'), ('Voltage Fluctuation / Low Voltage', 'Voltage Fluctuation / Low Voltage'), ('Meter Issues', 'Meter Issues'), ('Billing and Payment', 'Billing and Payment'), ('Transformer Fault', 'Transformer Fault'), ('Pole / Wire / Electrical Hazard', 'Pole / Wire / Electrical Hazard'), ('New Connection / Service Request', 'New Connection / Service Request'), ('Street/Public Electrical Infrastructure', 'Street/Public Electrical Infrastructure'), ('Power Theft / Unauthorized Connection', 'Power Theft / Unauthorized Connection'), ('General Consumer Services', 'General Consumer Services')], help_text='AI Predicted Category', max_length=100, null=True)),
                ('verified_category', models.CharField(blank=True, choices=[('Power Outage / No Supply', 'Power Outage / No Supply'), ('Voltage Fluctuation / Low Voltage', 'Voltage Fluctuation / Low Voltage'), ('Meter Issues', 'Meter Issues'), ('Billing and Payment', 'Billing and Payment'), ('Transformer Fault', 'Transformer Fault'), ('Pole / Wire / Electrical Hazard', 'Pole / Wire / Electrical Hazard'), ('New Connection / Service Request', 'New Connection / Service Request'), ('Street/Public Electrical Infrastructure', 'Street/Public Electrical Infrastructure'), ('Power Theft / Unauthorized Connection', 'Power Theft / Unauthorized Connection'), ('General Consumer Services', 'General Consumer Services')], help_text='Human verified Category', max_length=100, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical Safety Hazard')], default='MEDIUM', max_length=20)),
                ('priority_source', models.CharField(choices=[('ML', 'Machine Learning Model'), ('RULE_BASED', 'Safety Rule Engine'), ('MANUAL', 'Human Officer Override')], default='RULE_BASED', max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('AI_CLASSIFIED', 'AI Classified'), ('PENDING_ASSIGNMENT', 'Pending Assignment'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'Cancelled')], db_index=True, default='SUBMITTED', max_length=30)),
                ('safety_risk_level', models.CharField(choices=[('NONE', 'No Immediate Hazard'), ('LOW', 'Low Risk'), ('HIGH', 'High Risk'), ('CRITICAL_HAZARD', 'Critical Electrical Hazard (Live Wire / Sparking)')], default='NONE', max_length=30)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('model_version', models.CharField(default='1.0.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='departments.electricalasset')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='departments.department')),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to=settings.AUTH_USER_MODEL)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to=settings.AUTH_USER_MODEL)),
                ('service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='departments.servicearea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_internal_note', models.BooleanField(default=False)),
                ('update_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='grievances.grievance')),
            ],
        ),
        migrations.CreateModel(
            name='GrievanceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('AI_CLASSIFIED', 'AI Classified'), ('PENDING_ASSIGNMENT', 'Pending Assignment'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'Cancelled')], max_length=30, null=True)),
                ('to_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('AI_CLASSIFIED', 'AI Classified'), ('PENDING_ASSIGNMENT', 'Pending Assignment'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('ESCALATED', 'Escalated'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='grievances.grievance')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['status', 'priority'], name='grievances__status_a58bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['created_at'], name='grievances__created_3ac0cd_idx'),
        ),
    ]
