# Generated by Django 6.1 on 2026-09-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0004_grievance_citizen_review'),
        ('sla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='breached_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='escalation_level',
            field=models.CharField(choices=[('NONE', 'Normal Operational Handling'), ('LEVEL_1', 'Level 1 — Section / Junior Engineer'), ('LEVEL_2', 'Level 2 — Assistant Engineer / Sub-Division'), ('LEVEL_3', 'Level 3 — Executive Engineer / Division'), ('LEVEL_4', 'Level 4 — Superintending Engineer / Circle')], db_index=True, default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='grievance',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievance',
            name='pause_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='paused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_grievances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievance',
            name='resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='sla_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='sla.slapolicy'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='sla_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ACTIVE', 'Active / Within SLA'), ('WARNING', 'SLA Warning'), ('BREACHED', 'SLA Breached'), ('PAUSED', 'SLA Clock Paused'), ('RESOLVED', 'Resolved Within SLA'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=30),
        ),
        migrations.AddField(
            model_name='grievance',
            name='total_paused_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
