# Generated by Django 6.1 on 2026-09-09 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grievances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_method', models.CharField(choices=[('AUTO_RECOMMENDED', 'Rule-Based Smart Recommendation'), ('MANUAL_ADMIN', 'Manual Administrator Assignment')], default='AUTO_RECOMMENDED', max_length=30)),
                ('recommendation_score', models.FloatField(default=1.0, help_text='Workload & location matching score')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_records_created', to=settings.AUTH_USER_MODEL)),
                ('assigned_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_records', to=settings.AUTH_USER_MODEL)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grievances.grievance')),
            ],
        ),
    ]
