# Generated by Django 6.1 on 2026-09-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical Safety Hazard')], max_length=20, unique=True)),
                ('resolution_target_hours', models.IntegerField(help_text='Target hours to resolve complaint')),
                ('escalation_threshold_hours', models.IntegerField(help_text='Hours after which escalation triggers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLAEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_level', models.CharField(choices=[('LEVEL_1', 'Level 1 - Ward Supervisor'), ('LEVEL_2', 'Level 2 - Executive Engineer'), ('LEVEL_3', 'Level 3 - Superintending Engineer')], default='LEVEL_1', max_length=20)),
                ('reason', models.TextField()),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='grievances.grievance')),
            ],
        ),
    ]
