# Generated by Django 6.1 on 2026-09-28 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('grievances', '0005_grievance_breached_at_grievance_escalation_level_and_more'),
        ('sla', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPauseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_at', models.DateTimeField(auto_now_add=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('reason_type', models.CharField(choices=[('WAITING_FOR_CONSUMER', 'Waiting for Consumer Input / Premises Access'), ('PARTS_PROCUREMENT', 'Spare Parts / Transformer Procurement in Transit'), ('SAFETY_CLEARANCE', 'Awaiting Safety / Civil Clearance'), ('SCHEDULED_SHUTDOWN', 'Scheduled Maintenance Window Coordination'), ('OTHER', 'Other Legitimate Administrative Reason')], default='WAITING_FOR_CONSUMER', max_length=50)),
                ('reason_notes', models.TextField()),
                ('duration_seconds', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-paused_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='slaescalation',
            options={'ordering': ['-escalated_at']},
        ),
        migrations.AlterModelOptions(
            name='slapolicy',
            options={'ordering': ['priority', '-target_minutes'], 'verbose_name': 'SLA Policy', 'verbose_name_plural': 'SLA Policies'},
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaescalation',
            name='escalated_to_designation',
            field=models.CharField(default='Junior Engineer', max_length=100),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='category',
            field=models.CharField(blank=True, choices=[('Power Outage / No Supply', 'Power Outage / No Supply'), ('Voltage Fluctuation / Low Voltage', 'Voltage Fluctuation / Low Voltage'), ('Meter Issues', 'Meter Issues'), ('Billing and Payment', 'Billing and Payment'), ('Transformer Fault', 'Transformer Fault'), ('Pole / Wire / Electrical Hazard', 'Pole / Wire / Electrical Hazard'), ('New Connection / Service Request', 'New Connection / Service Request'), ('Street/Public Electrical Infrastructure', 'Street/Public Electrical Infrastructure'), ('Power Theft / Unauthorized Connection', 'Power Theft / Unauthorized Connection'), ('General Consumer Services', 'General Consumer Services')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_policies', to='departments.department'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='name',
            field=models.CharField(default='Standard SLA Policy', max_length=150),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='service_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_policies', to='departments.servicearea'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='sla_clock_type',
            field=models.CharField(choices=[('24_HOURS', '24/7 Continuous Utility Clock'), ('BUSINESS_HOURS', 'Business Hours (09:00 - 18:00)')], default='24_HOURS', max_length=30),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='target_minutes',
            field=models.IntegerField(default=1440, help_text='Target resolution time in minutes'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='warning_minutes',
            field=models.IntegerField(default=120, help_text='Warning threshold before deadline in minutes'),
        ),
        migrations.AlterField(
            model_name='slaescalation',
            name='escalation_level',
            field=models.CharField(choices=[('LEVEL_1', 'Level 1 — Section / Junior Engineer'), ('LEVEL_2', 'Level 2 — Assistant Engineer / Sub-Division'), ('LEVEL_3', 'Level 3 — Executive Engineer / Division'), ('LEVEL_4', 'Level 4 — Superintending Engineer / Circle')], default='LEVEL_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='escalation_threshold_hours',
            field=models.IntegerField(default=2, help_text='Hours after breach before next escalation level'),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical Safety Hazard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='resolution_target_hours',
            field=models.IntegerField(default=24, help_text='Target hours to resolve complaint'),
        ),
        migrations.AddConstraint(
            model_name='slaescalation',
            constraint=models.UniqueConstraint(fields=('grievance', 'escalation_level'), name='unique_grievance_escalation_level'),
        ),
        migrations.AddField(
            model_name='slapauselog',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_pauses', to='grievances.grievance'),
        ),
        migrations.AddField(
            model_name='slapauselog',
            name='paused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_sla_pauses', to=settings.AUTH_USER_MODEL),
        ),
    ]
