# Generated by Django 6.1 on 2026-09-25 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Designates whether the user's identity/email/mobile has been verified."),
        ),
        migrations.CreateModel(
            name='AccountVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the verification code', max_length=128)),
                ('purpose', models.CharField(choices=[('VERIFY_ACCOUNT', 'Account Verification'), ('RESET_PASSWORD', 'Password Reset')], default='VERIFY_ACCOUNT', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_ac_user_id_047d19_idx')],
            },
        ),
    ]
