# Generated by Django 6.1 on 2026-09-28 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_unique_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of single-use invitation token', max_length=128)),
                ('designation', models.CharField(default='System Administrator', max_length=100)),
                ('department', models.CharField(default='ADMINISTRATION', max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Administrative Approval'), ('APPROVED', 'Approved & Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING_APPROVAL', max_length=20),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_officers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='circle',
            field=models.CharField(blank=True, default='', help_text='MSEDCL Circle', max_length=100),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='department',
            field=models.CharField(choices=[('POWER_SUPPLY', 'Power Supply & Outages'), ('METERING', 'Metering & Apparatus'), ('BILLING', 'Billing & Revenue'), ('MAINTENANCE', 'Infrastructure Maintenance'), ('EMERGENCY_SAFETY', 'Emergency & Safety'), ('COMMERCIAL', 'Commercial Services')], default='POWER_SUPPLY', max_length=50),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='division',
            field=models.CharField(blank=True, default='', help_text='MSEDCL Division', max_length=100),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='office_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='official_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='region',
            field=models.CharField(blank=True, default='', help_text='MSEDCL Region (e.g. Pune, Mumbai, Nagpur)', max_length=100),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='section',
            field=models.CharField(blank=True, default='', help_text='MSEDCL Section / Branch', max_length=100),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='subdivision',
            field=models.CharField(blank=True, default='', help_text='MSEDCL Sub-Division', max_length=100),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Contact Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='employee_id',
            field=models.CharField(help_text='Unique MSEDCL Staff Identification Number', max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='officerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('official_email__isnull', False), models.Q(('official_email', ''), _negated=True)), fields=('official_email',), name='unique_staff_official_email'),
        ),
        migrations.AddConstraint(
            model_name='officerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('official_mobile__isnull', False), models.Q(('official_mobile', ''), _negated=True)), fields=('official_mobile',), name='unique_staff_official_mobile'),
        ),
        migrations.AddField(
            model_name='admininvitation',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_admin_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='admininvitation',
            index=models.Index(fields=['token_hash', 'is_accepted'], name='accounts_ad_token_h_48da5b_idx'),
        ),
    ]
