# Generated by Django 6.1 on 2026-09-09 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_name', models.CharField(max_length=100)),
                ('division_name', models.CharField(max_length=100)),
                ('substation_name', models.CharField(max_length=150)),
                ('pincode', models.CharField(db_index=True, max_length=10)),
                ('district', models.CharField(default='Pune', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['circle_name', 'division_name'], name='departments_circle__2cc8b6_idx'), models.Index(fields=['pincode'], name='departments_pincode_898b9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ElectricalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=100, unique=True)),
                ('asset_type', models.CharField(choices=[('TRANSFORMER', 'Distribution Transformer'), ('FEEDER', '11kV / 33kV Feeder Line'), ('POLE', 'Electrical Pole'), ('SUBSTATION', 'Substation Unit'), ('METER', 'Consumer Smart/Static Meter')], max_length=30)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('FAULTY', 'Faulty / Damaged'), ('MAINTENANCE', 'Under Maintenance')], default='OPERATIONAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='departments.servicearea')),
            ],
        ),
    ]
